---
title: "Linear_Models"
author: "Keedo"
date: "November 10, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)

set.seed(1)
```


### Examples

Look at AirBnB data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(boro = neighbourhood_group,
         neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

Fit a linear model for price as an outcome.

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

# Price is my outcome
# stars and boro is my 2 predictors  (One main effect for stars, one main effect for boro)
```

Look at some summaries.

```{r}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

Look at better summaries.
```{r}
broom::tidy(fit)

# Spits this in a manner that is a dataframe.
# Can do some data manipulation if I want.


fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```

Look at other summaries:

```{r}
fit %>%
  broom::glance()

# Glance is going to extract the quick summaries related to mdel fit. 
# will extract the most commonly used information from model fit
```
Be careful with factors...

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(boro = fct_infreq(boro),
         room_type = fct_infreq(room_type))

# First converting boro into a factor and is putting it in order of frequency rather than in alphabetical order.

# Most common room_type will be reference category.

fit = lm(price ~ stars + boro, data = nyc_airbnb)

fit %>%
  broom::tidy()

# Now rather than be compared to the Bonx, Manhattan is now the reference category.
```

### Diagnostics

```{r}
fitted.values(fit)
# Don't ever use this


modelr::add_residuals(nyc_airbnb, fit) %>%
  ggplot(aes(x = boro, y =resid)) + geom_boxplot()

#add_residulas - 1st argument into the function is the dataset that I want to operate on
# 2nd argument is the model to add residuals for

modelr::add_residuals(nyc_airbnb, fit) %>%
  ggplot(aes(x = stars, y =resid)) + geom_point()


modelr::add_predictions(nyc_airbnb, fit) %>%
  ggplot(aes(x = stars, y =pred, color = boro)) + geom_point()

# This shows the fitted values that go along with this thing; not the residuals any more
```

### Testing
```{r}
# What is the effect of stars and is it statistically significant?
  
fit %>%
  broom::tidy()
```

Compare nested models

```{r}
fit_null = lm(price ~ stars + boro, data = nyc_airbnb)

fit_alt = lm(price ~ stars + boro + room_type, data  = nyc_airbnb)

# The null model is nested within the alternative model because the alternative model starts at the null model and adds two terms to it

anova(fit_null, fit_alt) %>%
  broom::tidy()

# Can only use ANOVA to compare nested models
```

### Nested data

```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)

# The '*' shows an interaction term - Effect measure modification

# 
```
Nesting and then fitting

```{r}
nest_lm_res =
  nyc_airbnb %>% 
  group_by(boro) %>% 
  nest() %>% 

  # The above step created a dataset specific to each of the 4 boros that he's interested in.
  # Let me start with the original dataset, group by 'boro' and then collapse all of the non- 'boro' variables inside of the Bronx, inside of Queens, inside of Brooklyn, inside of Manhatttan 
  
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest()
```



